{{- if and .Values.staking.enabled (not .Values.staking.config.existingSecret) .Values.staking.config.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "juno.fullname" . }}-staking-config
  labels:
    app.kubernetes.io/component: staking
    {{- include "juno.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- .Values.staking.config.data | toPrettyJson | nindent 4 }}
{{- end }}
