apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juno-data
  namespace: starknet
  labels:
    app: juno
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
