apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: starknet
  labels:
    app: loki
    component: logging
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
  type: ClusterIP
